export const data = [
  {
    id: 1,
    title: 'Math',
    desc: 'Do homework and read slide',
    priority: 'High',
    createAt: '11/11/2022',
    status: 'Doing',
    exist: true,
  },
  {
    id: 2,
    title: 'History',
    desc: 'Do homework, read slide and docs',
    priority: 'Low',
    createAt: '11/11/2022',
    status: 'Todo',
    exist: false,
  },
  {
    id: 3,
    title: 'Story',
    desc: 'Do homework, read slide and docs',
    priority: 'Low',
    createAt: '11/11/2022',
    status: 'Todo',
    exist: false,
  },
  {
    id: 4,
    title: 'Chill',
    desc: 'Do homework and read slide',
    priority: 'High',
    createAt: '11/11/2022',
    status: 'Doing',
    exist: true,
  },
  {
    id: 5,
    title: 'Gym',
    desc: 'Do homework, read slide and docs',
    priority: 'Normal',
    createAt: '11/11/2022',
    status: 'Todo',
    exist: false,
  },
  {
    id: 6,
    title: 'Football',
    desc: 'Do homework, read slide and docs',
    priority: 'Normal',
    createAt: '11/11/2022',
    status: 'Todo',
    exist: false,
  },
];
